meta:
  file:
    extension: xlsx
    name: "sample"
blueprint:
  - name: header_info
    type: left
    conditions:
      - column: [1]
    fields:
      - name: currency
        position: 6
      - name: cashier
        position: 2
